class CfgVehicles {
	class B_Kitbag_rgr;
	class JLTS_Clone_P2_DC15A;
	class JLTS_Clone_P2_DC15S;
	class JLTS_Clone_P2_DC15AUGL;
	class JLTS_Clone_P2_DP23;
	class JLTS_Clone_P2_AT;
	class JLTS_Clone_P2_captain;
	class JLTS_Clone_P2_commander;
	class JLTS_Clone_P2_corporal;
	class JLTS_Clone_P2_jump;
	class JLTS_Clone_P2_lieutenant;
	class JLTS_Clone_P2_major;
	class JLTS_Clone_P2_marksman;
	class JLTS_Clone_P2_medic;
	class JLTS_Clone_P2_eod;
	class JLTS_Clone_P2_RTO;
	class JLTS_Clone_P2_sergeant;
	class JLTS_Clone_P2_sergeantmajor;
	class JLTS_Clone_P2_AR;

	class 87th_Backpack: B_Kitbag_rgr
	{
		author="Stim";
		scope=2;
		picture="\MRC\JLTS\characters\CloneArmor\data\ui\Clone_backpack_ui_ca.paa";
		displayName="87th Backpack";
		model="\MRC\JLTS\characters\CloneArmor\CloneBackpack.p3d";
		maximumLoad = 200;
		hiddenSelections[]=
		{
			"camo1"
		};
        hiddenSelectionsTextures[] = {QPATHTOF("data\accessories\87th_Backpack_co.paa")};
	};
    class 87th_Medic_Backpack: 87th_Backpack
	{
		displayName="87th Medic Backpack";
		maximumLoad = 400;
        hiddenSelectionsTextures[] = {QPATHTOF("data\accessories\87th_Medic_Backpack_co.paa")};
	};
	class 87th_RTO_Backpack: 87th_Backpack
	{
		picture="\MRC\JLTS\characters\CloneArmor\data\ui\Clone_backpack_ui_ca.paa";
		displayName="87th RTO Backpack";
		model="\MRC\JLTS\characters\CloneArmor\CloneBackpackRTO.p3d";
		hiddenSelections[]=
		{
			"camo",
			"camo1"
		};
        hiddenSelectionsTextures[] = {
            QPATHTOF("data\accessories\RTO_Screen_co.paa"),
            QPATHTOF("data\accessories\87th_Backpack_co.paa")
        };
		tf_dialog="JLTS_clone_rto_radio_dialog";
		tf_dialogUpdate="call TFAR_fnc_updateLRDialogToChannel;";
		tf_encryptionCode="tf_west_radio_code";
		tf_hasLRradio=1;
		tf_range=25000;
		tf_subtype="digital_lr";
	};
	class 87th_Clone_DC15A: JLTS_Clone_P2_DC15A
	{
		displayName="Clone Trooper (DC-15A)";
		editorPreview="x\data\ui\editorPreviews\87th_Clone_DC15A.jpg";
		faction = "87th_Legion";
		editorSubcategory = "87th_Troopers";
		uniformClass="87th_Trooper_Uniform";
		hiddenSelectionsTextures[] = {
            QPATHTOF("data\armor\87th_Chest_co.paa"),
            QPATHTOF("data\armor\87th_Legs_co.paa")
        };
		linkedItems[]=
		{
			"87th_Trooper_Helmet",
			"JLTS_NVG_droid_chip_2",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"87th_Trooper_Helmet",
			"JLTS_NVG_droid_chip_2",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		weapons[]=
		{
			"87th_3AS_DC15A_F",
			"JLTS_DC17SA",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"87th_3AS_DC15A_F",
			"JLTS_DC17SA",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"3AS_45Rnd_EC50_Mag",
			"3AS_45Rnd_EC50_Mag",
			"3AS_45Rnd_EC50_Mag",
			"3AS_45Rnd_EC50_Mag",
			"3AS_45Rnd_EC50_Mag",
			"3AS_45Rnd_EC50_Mag",
			"3AS_45Rnd_EC50_Mag",
			"3AS_45Rnd_EC50_Mag",
			"3AS_45Rnd_EC50_Mag",
			"3AS_45Rnd_EC50_Mag",
			"JLTS_DC17SA_mag",
			"JLTS_DC17SA_mag",
			"JLTS_DC17SA_mag",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green",
			"JLTS_stun_mag_long",
			"JLTS_stun_mag_long",
			"HandGrenade",
			"HandGrenade"
		};
		respawnMagazines[]=
		{
			"3AS_45Rnd_EC50_Mag",
			"3AS_45Rnd_EC50_Mag",
			"3AS_45Rnd_EC50_Mag",
			"3AS_45Rnd_EC50_Mag",
			"3AS_45Rnd_EC50_Mag",
			"3AS_45Rnd_EC50_Mag",
			"3AS_45Rnd_EC50_Mag",
			"3AS_45Rnd_EC50_Mag",
			"3AS_45Rnd_EC50_Mag",
			"3AS_45Rnd_EC50_Mag",
			"JLTS_DC17SA_mag",
			"JLTS_DC17SA_mag",
			"JLTS_DC17SA_mag",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green",
			"JLTS_stun_mag_long",
			"JLTS_stun_mag_long",
			"HandGrenade",
			"HandGrenade"
		};
	};
	class 87th_Clone_DC15S: JLTS_Clone_P2_DC15S
	{
		displayName="Clone Trooper (DC-15S)";
		editorPreview="x\data\ui\editorPreviews\87th_Clone_DC15S.jpg";
		faction = "87th_Legion";
		editorSubcategory = "87th_Troopers";
		uniformClass="87th_Trooper_Uniform";
		hiddenSelectionsTextures[] = {
            QPATHTOF("data\armor\87th_Chest_co.paa"),
            QPATHTOF("data\armor\87th_Legs_co.paa")
        };
		linkedItems[]=
		{
			"87th_Trooper_Helmet",
			"JLTS_NVG_droid_chip_2",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"87th_Trooper_Helmet",
			"JLTS_NVG_droid_chip_2",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		weapons[]=
		{
			"87th_3AS_DC15S_F",
			"JLTS_DC17SA",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"87th_3AS_DC15S_F",
			"JLTS_DC17SA",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"JLTS_DC17SA_mag",
			"JLTS_DC17SA_mag",
			"JLTS_DC17SA_mag",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green",
			"JLTS_stun_mag_long",
			"JLTS_stun_mag_long",
			"HandGrenade",
			"HandGrenade"
		};
		respawnMagazines[]=
		{
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"JLTS_DC17SA_mag",
			"JLTS_DC17SA_mag",
			"JLTS_DC17SA_mag",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green",
			"JLTS_stun_mag_long",
			"JLTS_stun_mag_long",
			"HandGrenade",
			"HandGrenade"
		};
	};
	class 87th_Clone_DC15AUGL: JLTS_Clone_P2_DC15AUGL {
		displayName="Clone Trooper (DC-15A UGL)";
		editorPreview="x\data\ui\editorPreviews\87th_Clone_DC15AUGL.jpg";
		faction = "87th_Legion";
		editorSubcategory = "87th_Troopers";
		uniformClass="87th_Trooper_Uniform";
		hiddenSelectionsTextures[] = {
            QPATHTOF("data\armor\87th_Chest_co.paa"),
            QPATHTOF("data\armor\87th_Legs_co.paa")
        };
		linkedItems[]=
		{
			"87th_Trooper_Helmet",
			"JLTS_CloneVestHolster",
			"JLTS_NVG_droid_chip_2",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"87th_Trooper_Helmet",
			"JLTS_CloneVestHolster",
			"JLTS_NVG_droid_chip_2",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		weapons[]=
		{
			"87th_3AS_DC15A_GL",
			"JLTS_DC17SA",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"87th_3AS_DC15A_GL",
			"JLTS_DC17SA",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"3AS_45Rnd_EC50_Mag",
			"3AS_45Rnd_EC50_Mag",
			"3AS_45Rnd_EC50_Mag",
			"3AS_45Rnd_EC50_Mag",
			"3AS_45Rnd_EC50_Mag",
			"3AS_45Rnd_EC50_Mag",
			"3AS_45Rnd_EC50_Mag",
			"3AS_45Rnd_EC50_Mag",
			"3AS_45Rnd_EC50_Mag",
			"3AS_45Rnd_EC50_Mag",
			"3Rnd_HE_Grenade_shell",
			"3Rnd_HE_Grenade_shell",
			"3Rnd_HE_Grenade_shell",
			"3Rnd_HE_Grenade_shell",
			"JLTS_DC17SA_mag",
			"JLTS_DC17SA_mag",
			"JLTS_DC17SA_mag",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green",
			"JLTS_stun_mag_long",
			"JLTS_stun_mag_long",
			"HandGrenade",
			"HandGrenade"
		};
		respawnMagazines[]=
		{
			"3AS_45Rnd_EC50_Mag",
			"3AS_45Rnd_EC50_Mag",
			"3AS_45Rnd_EC50_Mag",
			"3AS_45Rnd_EC50_Mag",
			"3AS_45Rnd_EC50_Mag",
			"3AS_45Rnd_EC50_Mag",
			"3AS_45Rnd_EC50_Mag",
			"3AS_45Rnd_EC50_Mag",
			"3AS_45Rnd_EC50_Mag",
			"3AS_45Rnd_EC50_Mag",
			"3Rnd_HE_Grenade_shell",
			"3Rnd_HE_Grenade_shell",
			"3Rnd_HE_Grenade_shell",
			"3Rnd_HE_Grenade_shell",
			"JLTS_DC17SA_mag",
			"JLTS_DC17SA_mag",
			"JLTS_DC17SA_mag",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green",
			"JLTS_stun_mag_long",
			"JLTS_stun_mag_long",
			"HandGrenade",
			"HandGrenade"
		};
	};
	class 87th_Clone_DP23: JLTS_Clone_P2_DP23 {
		displayName="Clone Trooper (DP-23)";
		editorPreview="x\data\ui\editorPreviews\87th_Clone_DP23.jpg";
		faction = "87th_Legion";
		editorSubcategory = "87th_Troopers";
		uniformClass="87th_Trooper_Uniform";
		hiddenSelectionsTextures[] = {
            QPATHTOF("data\armor\87th_Chest_co.paa"),
            QPATHTOF("data\armor\87th_Legs_co.paa")
        };
		linkedItems[]=
		{
			"87th_Trooper_Helmet",
			"JLTS_NVG_droid_chip_2",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"87th_Trooper_Helmet",
			"JLTS_NVG_droid_chip_2",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
	};
	class 87th_Clone_AT: JLTS_Clone_P2_AT {
		displayName="Clone AT Trooper";
		editorPreview="x\data\ui\editorPreviews\87th_Clone_AT.jpg";
		faction = "87th_Legion";
		editorSubcategory = "87th_Troopers";
		uniformClass="87th_Trooper_Uniform";
		hiddenSelectionsTextures[] = {
            QPATHTOF("data\armor\87th_Chest_co.paa"),
            QPATHTOF("data\armor\87th_Legs_co.paa")
        };
		linkedItems[]=
		{
			"87th_Trooper_Helmet",,
			"JLTS_NVG_droid_chip_2",
			"JLTS_CloneVestAirborne",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"87th_Trooper_Helmet",,
			"JLTS_NVG_droid_chip_2",
			"JLTS_CloneVestAirborne",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		weapons[]=
		{
			"87th_3AS_DC15S_F",
			"JLTS_DC17SA",
			"JLTS_RPS6",
			"SWLB_clone_binocular",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"87th_3AS_DC15S_F",
			"JLTS_DC17SA",
			"JLTS_RPS6",
			"SWLB_clone_binocular",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"JLTS_RPS6_mag",
			"JLTS_RPS6_mag",
			"JLTS_RPS6_mag",
			"JLTS_DC17SA_mag",
			"JLTS_DC17SA_mag",
			"JLTS_DC17SA_mag",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green",
			"JLTS_stun_mag_long",
			"JLTS_stun_mag_long",
			"HandGrenade",
			"HandGrenade"
		};
		respawnMagazines[]=
		{
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"JLTS_RPS6_mag",
			"JLTS_RPS6_mag",
			"JLTS_RPS6_mag",
			"JLTS_DC17SA_mag",
			"JLTS_DC17SA_mag",
			"JLTS_DC17SA_mag",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green",
			"JLTS_stun_mag_long",
			"JLTS_stun_mag_long",
			"HandGrenade",
			"HandGrenade"
		};
	};
	class 87th_Clone_Captain: JLTS_Clone_P2_captain {
		displayName="Clone Captain";
		editorPreview="x\data\ui\editorPreviews\87th_Clone_Captain.jpg";
		faction = "87th_Legion";
		editorSubcategory = "87th_Troopers";
		uniformClass="87th_Trooper_Uniform";
		hiddenSelectionsTextures[] = {
            QPATHTOF("data\armor\87th_Chest_co.paa"),
            QPATHTOF("data\armor\87th_Legs_co.paa")
        };
		linkedItems[]=
		{
			"87th_Trooper_Helmet",
			"87th_NVG",
			"87th_Officer_Accessories",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"87th_Trooper_Helmet",
			"87th_NVG",
			"87th_Officer_Accessories",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		weapons[]=
		{
			"87th_3AS_DC15S_F",
			"JLTS_DC17SA",
			"SWLB_clone_binocular",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"87th_3AS_DC15S_F",
			"JLTS_DC17SA",
			"SWLB_clone_binocular",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"JLTS_DC17SA_mag",
			"JLTS_DC17SA_mag",
			"JLTS_DC17SA_mag",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green",
			"JLTS_stun_mag_long",
			"JLTS_stun_mag_long",
			"HandGrenade",
			"HandGrenade"
		};
		respawnMagazines[]=
		{
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"JLTS_DC17SA_mag",
			"JLTS_DC17SA_mag",
			"JLTS_DC17SA_mag",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green",
			"JLTS_stun_mag_long",
			"JLTS_stun_mag_long",
			"HandGrenade",
			"HandGrenade"
		};
	};
	class 87th_Clone_Commander: JLTS_Clone_P2_commander {
		displayName="Clone Commander";
		editorPreview="x\data\ui\editorPreviews\87th_Clone_Commander.jpg";
		faction = "87th_Legion";
		editorSubcategory = "87th_Troopers";
		uniformClass="87th_Trooper_Uniform";
		hiddenSelectionsTextures[] = {
            QPATHTOF("data\armor\87th_Chest_co.paa"),
            QPATHTOF("data\armor\87th_Legs_co.paa")
        };
		linkedItems[]=
		{
			"87th_Commander_Helmet",
			"JLTS_CloneNVGMC",
			"87th_Commander_Accessories",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		backpack="JLTS_Clone_jumppack_mc";
		respawnLinkedItems[]=
		{
			"87th_Commander_Helmet",
			"JLTS_CloneNVGMC",
			"87th_Commander_Accessories",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		weapons[]=
		{
			"87th_3AS_DC15S_F",
			"JLTS_DC17SA",
			"SWLB_clone_binocular",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"87th_3AS_DC15S_F",
			"JLTS_DC17SA",
			"SWLB_clone_binocular",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"JLTS_DC17SA_mag",
			"JLTS_DC17SA_mag",
			"JLTS_DC17SA_mag",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green",
			"JLTS_stun_mag_long",
			"JLTS_stun_mag_long",
			"HandGrenade",
			"HandGrenade"
		};
		respawnMagazines[]=
		{
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"JLTS_DC17SA_mag",
			"JLTS_DC17SA_mag",
			"JLTS_DC17SA_mag",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green",
			"JLTS_stun_mag_long",
			"JLTS_stun_mag_long",
			"HandGrenade",
			"HandGrenade"
		};
	};
	class 87th_Clone_Corporal: JLTS_Clone_P2_corporal
	{
		displayName="Clone Corporal";
		editorPreview="x\data\ui\editorPreviews\87th_Clone_Corporal.jpg";
		faction = "87th_Legion";
		editorSubcategory = "87th_Troopers";
		uniformClass="87th_Trooper_Uniform";
		hiddenSelectionsTextures[] = {
            QPATHTOF("data\armor\87th_Chest_co.paa"),
            QPATHTOF("data\armor\87th_Legs_co.paa")
        };
		linkedItems[]=
		{
			"87th_Trooper_Helmet",
			"87th_NVG",
			"JLTS_CloneVestHolster",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"87th_Trooper_Helmet",
			"87th_NVG",
			"JLTS_CloneVestHolster",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		weapons[]=
		{
			"87th_3AS_DC15C_GL",
			"JLTS_DC17SA",
			"SWLB_clone_binocular",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"87th_3AS_DC15C_GL",
			"JLTS_DC17SA",
			"SWLB_clone_binocular",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"3AS_40Rnd_EC40_Mag",
			"3AS_40Rnd_EC40_Mag",
			"3AS_40Rnd_EC40_Mag",
			"3AS_40Rnd_EC40_Mag",
			"3AS_40Rnd_EC40_Mag",
			"3AS_40Rnd_EC40_Mag",
			"3AS_40Rnd_EC40_Mag",
			"3AS_40Rnd_EC40_Mag",
			"3AS_40Rnd_EC40_Mag",
			"3AS_40Rnd_EC40_Mag",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"JLTS_DC17SA_mag",
			"JLTS_DC17SA_mag",
			"JLTS_DC17SA_mag",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green",
			"JLTS_stun_mag_long",
			"JLTS_stun_mag_long",
			"HandGrenade",
			"HandGrenade"
		};
		respawnMagazines[]=
		{
			"3AS_40Rnd_EC40_Mag",
			"3AS_40Rnd_EC40_Mag",
			"3AS_40Rnd_EC40_Mag",
			"3AS_40Rnd_EC40_Mag",
			"3AS_40Rnd_EC40_Mag",
			"3AS_40Rnd_EC40_Mag",
			"3AS_40Rnd_EC40_Mag",
			"3AS_40Rnd_EC40_Mag",
			"3AS_40Rnd_EC40_Mag",
			"3AS_40Rnd_EC40_Mag",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"JLTS_DC17SA_mag",
			"JLTS_DC17SA_mag",
			"JLTS_DC17SA_mag",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green",
			"JLTS_stun_mag_long",
			"JLTS_stun_mag_long",
			"HandGrenade",
			"HandGrenade"
		};
	};
	class 87th_Clone_Jumper: JLTS_Clone_P2_jump
	{
		displayName="Clone Jet Trooper";
		editorPreview="x\data\ui\editorPreviews\87th_Clone_Jumper.jpg";
		faction = "87th_Legion";
		editorSubcategory = "87th_Troopers";
		uniformClass="87th_Trooper_Uniform";
		hiddenSelectionsTextures[] = {
            QPATHTOF("data\armor\87th_Chest_co.paa"),
            QPATHTOF("data\armor\87th_Legs_co.paa")
        };
		linkedItems[]=
		{
			"87th_Trooper_Helmet",
			"SWLB_CEE_Clone_Scarf_White",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		backpack="JLTS_Clone_jumppack_JT12";
		respawnLinkedItems[]=
		{
			"87th_Trooper_Helmet",
			"SWLB_CEE_Clone_Scarf_White",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		weapons[]=
		{
			"87th_3AS_DC15S_F",
			"JLTS_DC17SA",
			"SWLB_clone_binocular",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"87th_3AS_DC15S_F",
			"JLTS_DC17SA",
			"SWLB_clone_binocular",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"JLTS_DC17SA_mag",
			"JLTS_DC17SA_mag",
			"JLTS_DC17SA_mag",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green",
			"JLTS_stun_mag_long",
			"JLTS_stun_mag_long",
			"HandGrenade",
			"HandGrenade"
		};
		respawnMagazines[]=
		{
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"JLTS_DC17SA_mag",
			"JLTS_DC17SA_mag",
			"JLTS_DC17SA_mag",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green",
			"JLTS_stun_mag_long",
			"JLTS_stun_mag_long",
			"HandGrenade",
			"HandGrenade"
		};
	}; 
	class 87th_Clone_Lieutenant: JLTS_Clone_P2_lieutenant {
		displayName="Clone Lieutenant";
		editorPreview="x\data\ui\editorPreviews\87th_Clone_Lieutenant.jpg";
		faction = "87th_Legion";
		editorSubcategory = "87th_Troopers";
		uniformClass="87th_Trooper_Uniform";
		hiddenSelectionsTextures[] = {
            QPATHTOF("data\armor\87th_Chest_co.paa"),
            QPATHTOF("data\armor\87th_Legs_co.paa")
        };
		linkedItems[]=
		{
			"87th_Trooper_Helmet",
			"JLTS_CloneNVGRange",
			"87th_Lieutenant_Accessories",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"87th_Trooper_Helmet",
			"JLTS_CloneNVGRange",
			"87th_Lieutenant_Accessories",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		weapons[]=
		{
			"87th_3AS_DC15S_F",
			"JLTS_DC17SA",
			"SWLB_clone_binocular",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"87th_3AS_DC15S_F",
			"JLTS_DC17SA",
			"SWLB_clone_binocular",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"JLTS_DC17SA_mag",
			"JLTS_DC17SA_mag",
			"JLTS_DC17SA_mag",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green",
			"JLTS_stun_mag_long",
			"JLTS_stun_mag_long",
			"HandGrenade",
			"HandGrenade"
		};
		respawnMagazines[]=
		{
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"JLTS_DC17SA_mag",
			"JLTS_DC17SA_mag",
			"JLTS_DC17SA_mag",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green",
			"JLTS_stun_mag_long",
			"JLTS_stun_mag_long",
			"HandGrenade",
			"HandGrenade"
		};
	};
	class 87th_Clone_Major: JLTS_Clone_P2_major {
		displayName="Clone Major";
		editorPreview="x\data\ui\editorPreviews\87th_Clone_Major.jpg";
		faction = "87th_Legion";
		editorSubcategory = "87th_Troopers";
		uniformClass="87th_Trooper_Uniform";
		hiddenSelectionsTextures[] = {
            QPATHTOF("data\armor\87th_Chest_co.paa"),
            QPATHTOF("data\armor\87th_Legs_co.paa")
        };
		linkedItems[]=
		{
			"87th_Trooper_Helmet",
			"JLTS_CloneNVGCC",
			"87th_Officer_Accessories",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"87th_Trooper_Helmet",
			"JLTS_CloneNVGCC",
			"87th_Officer_Accessories",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		weapons[]=
		{
			"87th_3AS_DC15S_F",
			"JLTS_DC17SA",
			"SWLB_clone_binocular",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"87th_3AS_DC15S_F",
			"JLTS_DC17SA",
			"SWLB_clone_binocular",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"JLTS_DC17SA_mag",
			"JLTS_DC17SA_mag",
			"JLTS_DC17SA_mag",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green",
			"JLTS_stun_mag_long",
			"JLTS_stun_mag_long",
			"HandGrenade",
			"HandGrenade"
		};
		respawnMagazines[]=
		{
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"JLTS_DC17SA_mag",
			"JLTS_DC17SA_mag",
			"JLTS_DC17SA_mag",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green",
			"JLTS_stun_mag_long",
			"JLTS_stun_mag_long",
			"HandGrenade",
			"HandGrenade"
		};
	};
	class 87th_Clone_Marksman: JLTS_Clone_P2_marksman {
		displayName="Clone Marksman";
		editorPreview="x\data\ui\editorPreviews\87th_Clone_Marksman.jpg";
		faction = "87th_Legion";
		editorSubcategory = "87th_Troopers";
		uniformClass="87th_Trooper_Uniform";
		hiddenSelectionsTextures[] = {
            QPATHTOF("data\armor\87th_Chest_co.paa"),
            QPATHTOF("data\armor\87th_Legs_co.paa")
        };
		linkedItems[]=
		{
			"87th_Trooper_Helmet",
			"87th_NVG",
			"JLTS_CloneVestRecon",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"87th_Trooper_Helmet",
			"87th_NVG",
			"JLTS_CloneVestRecon",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		weapons[]=
		{
			"JLTS_DW32S",
			"JLTS_DC17SA",
			"SWLB_clone_binocular",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"JLTS_DW32S",
			"JLTS_DC17SA",
			"SWLB_clone_binocular",
			"Throw",
			"Put"
		};
	};
	class 87th_Clone_Medic: JLTS_Clone_P2_medic {
		displayName="Clone Medic";
		editorPreview="x\data\ui\editorPreviews\87th_Clone_Medic.jpg";
		faction = "87th_Legion";
		editorSubcategory = "87th_Troopers";
		uniformClass="87th_Trooper_Uniform";
		hiddenSelectionsTextures[] = {
            QPATHTOF("data\armor\87th_Chest_co.paa"),
            QPATHTOF("data\armor\87th_Legs_co.paa")
        };
		backpack="87th_Medic_Backpack";
		linkedItems[]=
		{
			"87th_Trooper_Helmet",,
			"JLTS_NVG_droid_chip_2",
			"JLTS_CloneVestSuspender",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"87th_Trooper_Helmet",,
			"JLTS_NVG_droid_chip_2",
			"JLTS_CloneVestSuspender",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		weapons[]=
		{
			"87th_3AS_DC15S_F",
			"JLTS_DC17SA",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"87th_3AS_DC15S_F",
			"JLTS_DC17SA",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"JLTS_DC17SA_mag",
			"JLTS_DC17SA_mag",
			"JLTS_DC17SA_mag",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green",
			"JLTS_stun_mag_long",
			"JLTS_stun_mag_long",
			"HandGrenade",
			"HandGrenade"
		};
		respawnMagazines[]=
		{
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"JLTS_DC17SA_mag",
			"JLTS_DC17SA_mag",
			"JLTS_DC17SA_mag",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green",
			"JLTS_stun_mag_long",
			"JLTS_stun_mag_long",
			"HandGrenade",
			"HandGrenade"
		};
		class EventHandlers
		{
			init="[_this select 0, ""JLTS_GAR_medic""] call BIS_fnc_setUnitInsignia;";
		};
	};
	class 87th_Clone_EOD: JLTS_Clone_P2_eod {
		displayName="Clone EOD";
		editorPreview="x\data\ui\editorPreviews\87th_Clone_EOD.jpg";
		faction = "87th_Legion";
		editorSubcategory = "87th_Troopers";
		uniformClass="87th_Trooper_Uniform";
		hiddenSelectionsTextures[] = {
            QPATHTOF("data\armor\87th_Chest_co.paa"),
            QPATHTOF("data\armor\87th_Legs_co.paa")
        };
		backpack="87th_Backpack";
		linkedItems[]=
		{
			"87th_Trooper_Helmet",,
			"JLTS_NVG_droid_chip_2",
			"JLTS_CloneVestSuspender",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"87th_Trooper_Helmet",,
			"JLTS_NVG_droid_chip_2",
			"JLTS_CloneVestSuspender",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		weapons[]=
		{
			"87th_3AS_DC15S_F",
			"JLTS_DC17SA",
			"SWLB_clone_binocular",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"87th_3AS_DC15S_F",
			"JLTS_DC17SA",
			"SWLB_clone_binocular",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"JLTS_DC17SA_mag",
			"JLTS_DC17SA_mag",
			"JLTS_DC17SA_mag",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green",
			"JLTS_stun_mag_long",
			"JLTS_stun_mag_long",
			"HandGrenade",
			"HandGrenade"
		};
		respawnMagazines[]=
		{
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"JLTS_DC17SA_mag",
			"JLTS_DC17SA_mag",
			"JLTS_DC17SA_mag",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green",
			"JLTS_stun_mag_long",
			"JLTS_stun_mag_long",
			"HandGrenade",
			"HandGrenade"
		};
		class EventHandlers
		{
			init="[_this select 0, ""JLTS_GAR_EOD""] call BIS_fnc_setUnitInsignia;";
		};
	};
	class 87th_Clone_RTO: JLTS_Clone_P2_RTO {
		displayName="Clone RTO";
		editorPreview="x\data\ui\editorPreviews\87th_Clone_RTO.jpg";
		faction = "87th_Legion";
		editorSubcategory = "87th_Troopers";
		uniformClass="87th_Trooper_Uniform";
		hiddenSelectionsTextures[] = {
            QPATHTOF("data\armor\87th_Chest_co.paa"),
            QPATHTOF("data\armor\87th_Legs_co.paa")
        };
		backpack="87th_RTO_Backpack"
		linkedItems[]=
		{
			"87th_Trooper_Helmet",
			"JLTS_NVG_droid_chip_2",
			"JLTS_CloneVestSuspender",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"87th_Trooper_Helmet",,
			"JLTS_NVG_droid_chip_2",
			"JLTS_CloneVestSuspender",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		weapons[]=
		{
			"87th_3AS_DC15S_F",
			"JLTS_DC17SA",
			"SWLB_clone_binocular",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"87th_3AS_DC15S_F",
			"JLTS_DC17SA",
			"SWLB_clone_binocular",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"JLTS_DC17SA_mag",
			"JLTS_DC17SA_mag",
			"JLTS_DC17SA_mag",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green",
			"JLTS_stun_mag_long",
			"JLTS_stun_mag_long",
			"HandGrenade",
			"HandGrenade"
		};
		respawnMagazines[]=
		{
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"JLTS_DC17SA_mag",
			"JLTS_DC17SA_mag",
			"JLTS_DC17SA_mag",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green",
			"JLTS_stun_mag_long",
			"JLTS_stun_mag_long",
			"HandGrenade",
			"HandGrenade"
		};
	};
	class 87th_Clone_Sergeant: JLTS_Clone_P2_sergeant {
		displayName="Clone Sergeant";
		editorPreview="x\data\ui\editorPreviews\87th_Clone_Sergeant.jpg";
		faction = "87th_Legion";
		editorSubcategory = "87th_Troopers";
		uniformClass="87th_Trooper_Uniform";
		hiddenSelectionsTextures[] = {
            QPATHTOF("data\armor\87th_Chest_co.paa"),
            QPATHTOF("data\armor\87th_Legs_co.paa")
        };
		linkedItems[]=
		{
			"87th_Trooper_Helmet",
			"87th_NVG",
			"87th_Kama",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"87th_Trooper_Helmet",
			"87th_NVG",
			"87th_Kama",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		weapons[]=
		{
			"87th_3AS_DC15S_F",
			"JLTS_DC17SA",
			"SWLB_clone_binocular",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"87th_3AS_DC15S_F",
			"JLTS_DC17SA",
			"SWLB_clone_binocular",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"JLTS_DC17SA_mag",
			"JLTS_DC17SA_mag",
			"JLTS_DC17SA_mag",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green",
			"JLTS_stun_mag_long",
			"JLTS_stun_mag_long",
			"HandGrenade",
			"HandGrenade"
		};
		respawnMagazines[]=
		{
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"JLTS_DC17SA_mag",
			"JLTS_DC17SA_mag",
			"JLTS_DC17SA_mag",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green",
			"JLTS_stun_mag_long",
			"JLTS_stun_mag_long",
			"HandGrenade",
			"HandGrenade"
		};
	};
	class 87th_Clone_SergeantMajor: JLTS_Clone_P2_sergeantmajor {
		displayName="Clone Sergeant-Major";
		editorPreview="x\data\ui\editorPreviews\87th_Clone_SergeantMajor.jpg";
		faction = "87th_Legion";
		editorSubcategory = "87th_Troopers";
		uniformClass="87th_Trooper_Uniform";
		hiddenSelectionsTextures[] = {
            QPATHTOF("data\armor\87th_Chest_co.paa"),
            QPATHTOF("data\armor\87th_Legs_co.paa")
        };
		linkedItems[]=
		{
			"87th_Trooper_Helmet",
			"JLTS_CloneNVGRange",
			"JLTS_CloneVestReconOfficer",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"87th_Trooper_Helmet",
			"JLTS_CloneNVGRange",
			"JLTS_CloneVestReconOfficer",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		weapons[]=
		{
			"87th_3AS_DC15S_F",
			"JLTS_DC17SA",
			"SWLB_clone_binocular",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"87th_3AS_DC15S_F",
			"JLTS_DC17SA",
			"SWLB_clone_binocular",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"JLTS_DC17SA_mag",
			"JLTS_DC17SA_mag",
			"JLTS_DC17SA_mag",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green",
			"JLTS_stun_mag_long",
			"JLTS_stun_mag_long",
			"HandGrenade",
			"HandGrenade"
		};
		respawnMagazines[]=
		{
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"3AS_60Rnd_EC30_mag",
			"JLTS_DC17SA_mag",
			"JLTS_DC17SA_mag",
			"JLTS_DC17SA_mag",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green",
			"JLTS_stun_mag_long",
			"JLTS_stun_mag_long",
			"HandGrenade",
			"HandGrenade"
		};
	};
	class 87th_Clone_AR: JLTS_Clone_P2_AR {
		displayName="Clone Heavy Trooper";
		editorPreview="x\data\ui\editorPreviews\87th_Clone_AR.jpg";
		faction = "87th_Legion";
		editorSubcategory = "87th_Troopers";
		uniformClass="87th_Trooper_Uniform";
		hiddenSelectionsTextures[] = {
            QPATHTOF("data\armor\87th_Chest_co.paa"),
            QPATHTOF("data\armor\87th_Legs_co.paa")
        };
		backpack="87th_Backpack";
		linkedItems[]=
		{
			"87th_Trooper_Helmet",
			"JLTS_NVG_droid_chip_2",
			"JLTS_CloneVestAirborneNCO",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"87th_Trooper_Helmet",
			"JLTS_NVG_droid_chip_2",
			"JLTS_CloneVestAirborneNCO",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		weapons[]=
		{
			"87th_3AS_DC15L_F",
			"JLTS_DC17SA",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"87th_3AS_DC15L_F",
			"JLTS_DC17SA",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"3AS_200Rnd_EC40_Mag",
			"3AS_200Rnd_EC40_Mag",
			"3AS_200Rnd_EC40_Mag",
			"3AS_200Rnd_EC40_Mag",
			"3AS_200Rnd_EC40_Mag",
			"3AS_200Rnd_EC40_Mag",
			"3AS_200Rnd_EC40_Mag",
			"3AS_200Rnd_EC40_Mag",
			"JLTS_DC17SA_mag",
			"JLTS_DC17SA_mag",
			"JLTS_DC17SA_mag",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green",
			"JLTS_stun_mag_long",
			"JLTS_stun_mag_long",
			"HandGrenade",
			"HandGrenade"
		};
		respawnMagazines[]=
		{
			"3AS_200Rnd_EC40_Mag",
			"3AS_200Rnd_EC40_Mag",
			"3AS_200Rnd_EC40_Mag",
			"3AS_200Rnd_EC40_Mag",
			"3AS_200Rnd_EC40_Mag",
			"3AS_200Rnd_EC40_Mag",
			"3AS_200Rnd_EC40_Mag",
			"3AS_200Rnd_EC40_Mag",
			"JLTS_DC17SA_mag",
			"JLTS_DC17SA_mag",
			"JLTS_DC17SA_mag",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green",
			"JLTS_stun_mag_long",
			"JLTS_stun_mag_long",
			"HandGrenade",
			"HandGrenade"
		};
	};
	class 87th_Clone_Sharpshooter: JLTS_Clone_P2_marksman {
		displayName="Clone Sharpshooter";
		editorPreview="x\data\ui\editorPreviews\87th_Clone_Sharpshooter.jpg";
		faction = "87th_Legion";
		editorSubcategory = "87th_Troopers";
		uniformClass="87th_Trooper_Uniform";
		hiddenSelectionsTextures[] = {
            QPATHTOF("data\armor\87th_Chest_co.paa"),
            QPATHTOF("data\armor\87th_Legs_co.paa")
        };
		linkedItems[]=
		{
			"87th_Trooper_Helmet",
			"JLTS_CloneNVG_spec",
			"JLTS_CloneVestReconNCO",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		respawnLinkedItems[]=
		{
			"87th_Trooper_Helmet",
			"JLTS_CloneNVG_spec",
			"JLTS_CloneVestReconNCO",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		weapons[]=
		{
			"87th_JLTS_DC15X",
			"JLTS_DC17SA",
			"SWLB_clone_binocular",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"87th_JLTS_DC15X",
			"JLTS_DC17SA",
			"SWLB_clone_binocular",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"JLTS_DC15X_mag",
			"JLTS_DC15X_mag",
			"JLTS_DC15X_mag",
			"JLTS_DC15X_mag",
			"JLTS_DC15X_mag",
			"JLTS_DC15X_mag",
			"JLTS_DC15X_mag",
			"JLTS_DC15X_mag",
			"JLTS_DC15X_mag",
			"JLTS_DC15X_mag",
			"JLTS_DC15X_mag",
			"JLTS_DC15X_mag",
			"JLTS_DC15X_mag",
			"JLTS_DC15X_mag",
			"JLTS_DC15X_mag",
			"JLTS_DC15X_mag",
			"JLTS_DC17SA_mag",
			"JLTS_DC17SA_mag",
			"JLTS_DC17SA_mag",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green",
			"JLTS_stun_mag_long",
			"JLTS_stun_mag_long",
			"HandGrenade",
			"HandGrenade"
		};
		respawnMagazines[]=
		{
			"JLTS_DC15X_mag",
			"JLTS_DC15X_mag",
			"JLTS_DC15X_mag",
			"JLTS_DC15X_mag",
			"JLTS_DC15X_mag",
			"JLTS_DC15X_mag",
			"JLTS_DC15X_mag",
			"JLTS_DC15X_mag",
			"JLTS_DC15X_mag",
			"JLTS_DC15X_mag",
			"JLTS_DC15X_mag",
			"JLTS_DC15X_mag",
			"JLTS_DC15X_mag",
			"JLTS_DC15X_mag",
			"JLTS_DC15X_mag",
			"JLTS_DC15X_mag",
			"JLTS_DC17SA_mag",
			"JLTS_DC17SA_mag",
			"JLTS_DC17SA_mag",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green",
			"JLTS_stun_mag_long",
			"JLTS_stun_mag_long",
			"HandGrenade",
			"HandGrenade"
		};
	};
	class 87th_ARF_DC15S: 87th_Clone_DC15S {
		displayName="ARF Trooper (DC-15S)";
		editorPreview="x\data\ui\editorPreviews\87th_ARF_DC15S.jpg";
		faction = "87th_Legion";
		editorSubcategory = "87th_ARF";
		linkedItems[]=
		{
			"87th_ARF_Helmet",
			"JLTS_CloneVestHolster",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		backpack="JLTS_Clone_belt_bag";
		respawnLinkedItems[]=
		{
			"87th_ARF_Helmet",
			"JLTS_CloneVestHolster",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		weapons[]=
		{
			"87th_3AS_DC15S_F",
			"JLTS_DC17SA",
			"SWLB_clone_binocular",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"87th_3AS_DC15S_F",
			"JLTS_DC17SA",
			"SWLB_clone_binocular",
			"Throw",
			"Put"
		};
	};
	class 87th_ARF_Sniper: 87th_Clone_Sharpshooter {
		displayName="ARF Sniper";
		editorPreview="x\data\ui\editorPreviews\87th_ARF_Sniper.jpg";
		faction = "87th_Legion";
		editorSubcategory = "87th_ARF";
		linkedItems[]=
		{
			"87th_ARF_Helmet",
			"JLTS_CloneVestHolster",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		backpack="JLTS_Clone_belt_bag";
		respawnLinkedItems[]=
		{
			"87th_ARF_Helmet",
			"JLTS_CloneVestHolster",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
	};
	class 87th_ARF_Spotter: 87th_Clone_Marksman {
		displayName="ARF Spotter";
		editorPreview="x\data\ui\editorPreviews\87th_ARF_Spotter.jpg";
		faction = "87th_Legion";
		editorSubcategory = "87th_ARF";
		linkedItems[]=
		{
			"87th_ARF_Helmet",
			"JLTS_CloneVestHolster",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		backpack="JLTS_Clone_belt_bag";
		respawnLinkedItems[]=
		{
			"87th_ARF_Helmet",
			"JLTS_CloneVestHolster",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
	};
	class 87th_ARF_JTAC: 87th_Clone_RTO {
		displayName="ARF JTAC";
		editorPreview="x\data\ui\editorPreviews\87th_ARF_JTAC.jpg";
		faction = "87th_Legion";
		editorSubcategory = "87th_ARF";
		linkedItems[]=
		{
			"87th_ARF_Helmet",
			"JLTS_CloneVestHolster",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		backpack="JLTS_Clone_RTO_pack";
		respawnLinkedItems[]=
		{
			"87th_ARF_Helmet",
			"JLTS_CloneVestHolster",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
	};
	class 87th_ARF_CLS: 87th_Clone_Medic {
		displayName="ARF Medic";
		editorPreview="x\data\ui\editorPreviews\87th_ARF_CLS.jpg";
		faction = "87th_Legion";
		editorSubcategory = "87th_ARF";
		linkedItems[]=
		{
			"87th_ARF_Helmet",
			"JLTS_CloneVestHolster",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		backpack="87th_Medic_Backpack";
		respawnLinkedItems[]=
		{
			"87th_ARF_Helmet",
			"JLTS_CloneVestHolster",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		weapons[]=
		{
			"87th_3AS_DC15S_F",
			"JLTS_DC17SA",
			"SWLB_clone_binocular",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"87th_3AS_DC15S_F",
			"JLTS_DC17SA",
			"SWLB_clone_binocular",
			"Throw",
			"Put"
		};
		class EventHandlers
		{
			init="[_this select 0, ""JLTS_GAR_medic""] call BIS_fnc_setUnitInsignia;";
		};
	};
	class 87th_ARF_NCO: 87th_Clone_Sergeant {
		displayName="ARF Sergeant";
		editorPreview="x\data\ui\editorPreviews\87th_ARF_NCO.jpg";
		faction = "87th_Legion";
		editorSubcategory = "87th_ARF";
		linkedItems[]=
		{
			"87th_ARF_Helmet",
			"JLTS_CloneVestReconOfficer",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		backpack="JLTS_Clone_belt_bag";
		respawnLinkedItems[]=
		{
			"87th_ARF_Helmet",
			"JLTS_CloneVestReconOfficer",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		weapons[]=
		{
			"87th_3AS_DC15S_F",
			"JLTS_DC17SA",
			"SWLB_clone_binocular",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"87th_3AS_DC15S_F",
			"JLTS_DC17SA",
			"SWLB_clone_binocular",
			"Throw",
			"Put"
		};
	};
	class 87th_ARF_Lieutenant: 87th_Clone_Lieutenant {
		displayName="ARF Lieutenant";
		editorPreview="x\data\ui\editorPreviews\87th_ARF_Lieutenant.jpg";
		faction = "87th_Legion";
		editorSubcategory = "87th_ARF";
		linkedItems[]=
		{
			"87th_ARF_Helmet",
			"87th_Lieutenant_Accessories",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		backpack="JLTS_Clone_belt_bag";
		respawnLinkedItems[]=
		{
			"87th_ARF_Helmet",
			"87th_Lieutenant_Accessories",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
	};
	class 87th_ARF_Captain: 87th_Clone_Captain {
		displayName="ARF Captain";
		editorPreview="x\data\ui\editorPreviews\87th_ARF_Captain.jpg";
		faction = "87th_Legion";
		editorSubcategory = "87th_ARF";
		linkedItems[]=
		{
			"87th_ARF_Helmet",
			"87th_Officer_Accessories",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		backpack="JLTS_Clone_belt_bag";
		respawnLinkedItems[]=
		{
			"87th_ARF_Helmet",
			"87th_Officer_Accessories",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
	};
	class 87th_ARF_Major: 87th_Clone_Commander {
		displayName="ARF Major";
		editorPreview="x\data\ui\editorPreviews\87th_ARF_Major.jpg";
		faction = "87th_Legion";
		editorSubcategory = "87th_ARF";
		linkedItems[]=
		{
			"87th_ARF_Helmet",
			"87th_Commander_Accessories",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		backpack="JLTS_Clone_jumppack_mc";
		respawnLinkedItems[]=
		{
			"87th_ARF_Helmet",
			"87th_Commander_Accessories",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
	};
	class 87th_BARC_DC15S: 87th_Clone_DC15S {
		displayName="BARC Trooper (DC-15S)";
		editorPreview="x\data\ui\editorPreviews\87th_BARC_DC15S.jpg";
		faction = "87th_Legion";
		editorSubcategory = "87th_BARC";
		linkedItems[]=
		{
			"87th_BARC_Helmet",
			"JLTS_NVG_droid_chip_2",
			"JLTS_CloneVestRecon",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		backpack="JLTS_Clone_belt_bag";
		respawnLinkedItems[]=
		{
			"87th_BARC_Helmet",
			"JLTS_NVG_droid_chip_2",
			"JLTS_CloneVestRecon",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		weapons[]=
		{
			"87th_3AS_DC15S_F",
			"JLTS_DC17SA",
			"SWLB_clone_binocular",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"87th_3AS_DC15S_F",
			"JLTS_DC17SA",
			"SWLB_clone_binocular",
			"Throw",
			"Put"
		};
	};
	class 87th_BARC_Sniper: 87th_Clone_Sharpshooter {
		displayName="BARC Sniper";
		editorPreview="x\data\ui\editorPreviews\87th_BARC_Sniper.jpg";
		faction = "87th_Legion";
		editorSubcategory = "87th_BARC";
		linkedItems[]=
		{
			"87th_BARC_Helmet",
			"87th_NVG",
			"JLTS_CloneVestRecon",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		backpack="JLTS_Clone_belt_bag";
		respawnLinkedItems[]=
		{
			"87th_BARC_Helmet",
			"87th_NVG",
			"JLTS_CloneVestRecon",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
	};
	class 87th_BARC_Spotter: 87th_Clone_Marksman {
		displayName="BARC Spotter";
		editorPreview="x\data\ui\editorPreviews\87th_BARC_Spotter.jpg";
		faction = "87th_Legion";
		editorSubcategory = "87th_BARC";
		linkedItems[]=
		{
			"87th_BARC_Helmet",
			"87th_NVG",
			"JLTS_CloneVestRecon",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		backpack="JLTS_Clone_belt_bag";
		respawnLinkedItems[]=
		{
			"87th_BARC_Helmet",
			"87th_NVG",
			"JLTS_CloneVestRecon",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
	};
	class 87th_BARC_JTAC: 87th_Clone_RTO {
		displayName="BARC JTAC";
		editorPreview="x\data\ui\editorPreviews\87th_BARC_JTAC.jpg";
		faction = "87th_Legion";
		editorSubcategory = "87th_BARC";
		linkedItems[]=
		{
			"87th_BARC_Helmet",
			"JLTS_NVG_droid_chip_2",
			"JLTS_CloneVestRecon",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		backpack="JLTS_Clone_RTO_pack";
		respawnLinkedItems[]=
		{
			"87th_BARC_Helmet",
			"JLTS_NVG_droid_chip_2",
			"JLTS_CloneVestRecon",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		weapons[]=
		{
			"87th_3AS_DC15S_F",
			"JLTS_DC17SA",
			"SWLB_clone_binocular",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"87th_3AS_DC15S_F",
			"JLTS_DC17SA",
			"SWLB_clone_binocular",
			"Throw",
			"Put"
		};
	};
	class 87th_BARC_CLS: 87th_Clone_Medic {
		displayName="BARC Medic";
		editorPreview="x\data\ui\editorPreviews\87th_BARC_CLS.jpg";
		faction = "87th_Legion";
		editorSubcategory = "87th_BARC";
		linkedItems[]=
		{
			"87th_BARC_Helmet",
			"JLTS_NVG_droid_chip_2",
			"JLTS_CloneVestRecon",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		backpack="87th_Medic_Backpack";
		respawnLinkedItems[]=
		{
			"87th_BARC_Helmet",
			"JLTS_NVG_droid_chip_2",
			"JLTS_CloneVestRecon",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		class EventHandlers
		{
			init="[_this select 0, ""JLTS_GAR_medic""] call BIS_fnc_setUnitInsignia;";
		};
	};
	class 87th_BARC_NCO: 87th_Clone_Sergeant {
		displayName="BARC Sergeant";
		editorPreview="x\data\ui\editorPreviews\87th_BARC_NCO.jpg";
		faction = "87th_Legion";
		editorSubcategory = "87th_BARC";
		linkedItems[]=
		{
			"87th_BARC_Helmet",
			"JLTS_CloneNVGRange",
			"JLTS_CloneVestReconOfficer",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		backpack="JLTS_Clone_belt_bag";
		respawnLinkedItems[]=
		{
			"87th_BARC_Helmet",
			"JLTS_CloneNVGRange",
			"JLTS_CloneVestReconOfficer",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		weapons[]=
		{
			"87th_3AS_DC15S_F",
			"JLTS_DC17SA",
			"SWLB_clone_binocular",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"87th_3AS_DC15S_F",
			"JLTS_DC17SA",
			"SWLB_clone_binocular",
			"Throw",
			"Put"
		};
	};
	class 87th_BARC_Lieutenant: 87th_Clone_Lieutenant {
		displayName="BARC Lieutenant";
		editorPreview="x\data\ui\editorPreviews\87th_BARC_Lieutenant.jpg";
		faction = "87th_Legion";
		editorSubcategory = "87th_BARC";
		linkedItems[]=
		{
			"87th_BARC_Helmet",
			"JLTS_CloneNVGRange",
			"87th_Lieutenant_Accessories",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		backpack="JLTS_Clone_belt_bag";
		respawnLinkedItems[]=
		{
			"87th_BARC_Helmet",
			"JLTS_CloneNVGRange",
			"87th_Lieutenant_Accessories",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
	};
	class 87th_BARC_Captain: 87th_Clone_Captain {
		displayName="BARC Captain";
		editorPreview="x\data\ui\editorPreviews\87th_BARC_Captain.jpg";
		faction = "87th_Legion";
		editorSubcategory = "87th_BARC";
		linkedItems[]=
		{
			"87th_BARC_Helmet",
			"87th_NVG",
			"87th_Officer_Accessories",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		backpack="JLTS_Clone_belt_bag";
		respawnLinkedItems[]=
		{
			"87th_BARC_Helmet",
			"87th_NVG",
			"87th_Officer_Accessories",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
	};
	class 87th_BARC_Major: 87th_Clone_Commander {
		displayName="BARC Major";
		editorPreview="x\data\ui\editorPreviews\87th_BARC_Major.jpg";
		faction = "87th_Legion";
		editorSubcategory = "87th_BARC";
		linkedItems[]=
		{
			"87th_BARC_Helmet",
			"JLTS_CloneNVGCC",
			"87th_Commander_Accessories",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		backpack="JLTS_Clone_jumppack_mc";
		respawnLinkedItems[]=
		{
			"87th_BARC_Helmet",
			"JLTS_CloneNVGCC",
			"87th_Commander_Accessories",
			"ItemMap",
			"JLTS_clone_comlink",
			"ItemCompass",
			"ItemWatch"
		};
	};
};