#define MAINPREFIX x
#define PREFIX ax87

#define VERSION     MAJOR.MINOR
#define VERSION_STR MAJOR.MINOR.PATCHLVL.BUILD
#define VERSION_AR  MAJOR,MINOR,PATCHLVL,BUILD

#define REQUIRED_VERSION 1.88
#define REQUIRED_CBA_VERSION {3,8,0}

#ifdef COMPONENT_BEAUTIFIED
    #define COMPONENT_NAME QUOTE(87th Legion - COMPONENT_BEAUTIFIED)
#else
    #define COMPONENT_NAME QUOTE(87th Legion - COMPONENT)
#endif