#define MAINPREFIX x
#define PREFIX ax87

#define TAG 87th
#define TAG_BR [##TAG##]

#define TITLE 87th Legion

#define FACTION_REP CLASS(Legion)

#define VERSION     MAJOR.MINOR
#define VERSION_STR MAJOR.MINOR.PATCHLVL
#define VERSION_AR  MAJOR,MINOR,PATCHLVL

#define REQUIRED_VERSION 1.88
#define REQUIRED_CBA_VERSION {3,8,0}

#ifdef COMPONENT_BEAUTIFIED
    #define COMPONENT_NAME QUOTE(TITLE - COMPONENT_BEAUTIFIED)
#else
    #define COMPONENT_NAME QUOTE(TITLE - COMPONENT)
#endif