class CfgGesturesMale
{
	class Default;
	class BlendAnims
	{
		AX87_Carry_arms[]=
		{
			"weapon",
			1,
			"RightShoulder",
			1,
			"RightArm",
			1,
			"RightArmRoll",
			1,
			"RightForeArm",
			1,
			"RightForeArmRoll",
			1,
			"RightHand",
			1,
			"RightHandRing",
			1,
			"RightHandPinky1",
			1,
			"RightHandPinky2",
			1,
			"RightHandPinky3",
			1,
			"RightHandRing1",
			1,
			"RightHandRing2",
			1,
			"RightHandRing3",
			1,
			"RightHandMiddle1",
			1,
			"RightHandMiddle2",
			1,
			"RightHandMiddle3",
			1,
			"RightHandIndex1",
			1,
			"RightHandIndex2",
			1,
			"RightHandIndex3",
			1,
			"RightHandThumb1",
			1,
			"RightHandThumb2",
			1,
			"RightHandThumb3",
			1,
			"Spine",
			0.1,
			"Spine1",
			0.1,
			"Spine2",
			0.89999998,
			"Spine3",
			0.89999998
		};
		AX87_sprint_arms[]=
		{
			"weapon",
			1,
			"RightShoulder",
			0.40000001,
			"RightArm",
			0.69999999,
			"RightArmRoll",
			1,
			"RightForeArm",
			0.1,
			"RightForeArmRoll",
			1,
			"RightHand",
			0.1,
			"RightHandRing",
			0.30000001,
			"RightHandPinky1",
			0.30000001,
			"RightHandPinky2",
			0.30000001,
			"RightHandPinky3",
			0.30000001,
			"RightHandRing1",
			0.30000001,
			"RightHandRing2",
			0.30000001,
			"RightHandRing3",
			0.30000001,
			"RightHandMiddle1",
			0.30000001,
			"RightHandMiddle2",
			0.30000001,
			"RightHandMiddle3",
			0.30000001,
			"RightHandIndex1",
			0.30000001,
			"RightHandIndex2",
			0.30000001,
			"RightHandIndex3",
			0.30000001,
			"RightHandThumb1",
			0.30000001,
			"RightHandThumb2",
			0.30000001,
			"RightHandThumb3",
			1,
			"LeftShoulder",
			1,
			"LeftArm",
			1,
			"LeftArmRoll",
			1,
			"LeftForeArm",
			1,
			"LeftForeArmRoll",
			1,
			"LeftHand",
			1,
			"LeftHandRing",
			1,
			"LeftHandPinky1",
			1,
			"LeftHandPinky2",
			1,
			"LeftHandPinky3",
			1,
			"LeftHandRing1",
			1,
			"LeftHandRing2",
			1,
			"LeftHandRing3",
			1,
			"LeftHandMiddle1",
			1,
			"LeftHandMiddle2",
			1,
			"LeftHandMiddle3",
			1,
			"LeftHandIndex1",
			1,
			"LeftHandIndex2",
			1,
			"LeftHandIndex3",
			1,
			"LeftHandThumb1",
			1,
			"LeftHandThumb2",
			1,
			"LeftHandThumb3",
			1,
			"Spine",
			0.30000001,
			"Spine1",
			0.30000001,
			"Spine2",
			0.80000001,
			"Spine3",
			0.80000001
		};
		AX87_carry_arms2[]=
		{
			"weapon",
			1,
			"RightShoulder",
			1,
			"RightArm",
			1,
			"RightArmRoll",
			1,
			"RightForeArm",
			1,
			"RightForeArmRoll",
			1,
			"RightHand",
			1,
			"RightHandRing",
			1,
			"RightHandPinky1",
			1,
			"RightHandPinky2",
			1,
			"RightHandPinky3",
			1,
			"RightHandRing1",
			1,
			"RightHandRing2",
			1,
			"RightHandRing3",
			1,
			"RightHandMiddle1",
			1,
			"RightHandMiddle2",
			1,
			"RightHandMiddle3",
			1,
			"RightHandIndex1",
			1,
			"RightHandIndex2",
			1,
			"RightHandIndex3",
			1,
			"RightHandThumb1",
			1,
			"RightHandThumb2",
			1,
			"RightHandThumb3",
			1,
			"LeftShoulder",
			1,
			"LeftArm",
			1,
			"LeftArmRoll",
			1,
			"LeftForeArm",
			1,
			"LeftForeArmRoll",
			1,
			"LeftHand",
			1,
			"LeftHandRing",
			1,
			"LeftHandPinky1",
			1,
			"LeftHandPinky2",
			1,
			"LeftHandPinky3",
			1,
			"LeftHandRing1",
			1,
			"LeftHandRing2",
			1,
			"LeftHandRing3",
			1,
			"LeftHandMiddle1",
			1,
			"LeftHandMiddle2",
			1,
			"LeftHandMiddle3",
			1,
			"LeftHandIndex1",
			1,
			"LeftHandIndex2",
			1,
			"LeftHandIndex3",
			1,
			"LeftHandThumb1",
			1,
			"LeftHandThumb2",
			1,
			"LeftHandThumb3",
			1,
			"Spine",
			0.1,
			"Spine1",
			0.1,
			"Spine2",
			0.89999998,
			"Spine3",
			0.89999998
		};
		AX87_carry_arms3[]=
		{
			"weapon",
			1,
			"RightShoulder",
			1,
			"RightArm",
			0.5,
			"RightArmRoll",
			1,
			"RightForeArm",
			1,
			"RightForeArmRoll",
			1,
			"RightHand",
			1,
			"RightHandRing",
			1,
			"RightHandPinky1",
			1,
			"RightHandPinky2",
			1,
			"RightHandPinky3",
			1,
			"RightHandRing1",
			1,
			"RightHandRing2",
			1,
			"RightHandRing3",
			1,
			"RightHandMiddle1",
			1,
			"RightHandMiddle2",
			1,
			"RightHandMiddle3",
			1,
			"RightHandIndex1",
			1,
			"RightHandIndex2",
			1,
			"RightHandIndex3",
			1,
			"RightHandThumb1",
			1,
			"RightHandThumb2",
			1,
			"RightHandThumb3",
			1,
			"LeftShoulder",
			1,
			"LeftArm",
			0.5,
			"LeftArmRoll",
			0.80000001,
			"LeftForeArm",
			0.1,
			"LeftForeArmRoll",
			1,
			"LeftHand",
			0.1,
			"LeftHandRing",
			1,
			"LeftHandPinky1",
			1,
			"LeftHandPinky2",
			1,
			"LeftHandPinky3",
			1,
			"LeftHandRing1",
			1,
			"LeftHandRing2",
			1,
			"LeftHandRing3",
			1,
			"LeftHandMiddle1",
			1,
			"LeftHandMiddle2",
			1,
			"LeftHandMiddle3",
			1,
			"LeftHandIndex1",
			1,
			"LeftHandIndex2",
			1,
			"LeftHandIndex3",
			1,
			"LeftHandThumb1",
			1,
			"LeftHandThumb2",
			1,
			"LeftHandThumb3",
			1,
			"Spine",
			0.1,
			"Spine1",
			0.1,
			"Spine2",
			0.2,
			"Spine3",
			0.2
		};
		AX87_Switch_arms[]=
		{
			"weapon",
			1,
			"RightShoulder",
			1,
			"RightArm",
			1,
			"RightArmRoll",
			1,
			"RightForeArm",
			1,
			"RightForeArmRoll",
			1,
			"RightHand",
			1,
			"RightHandRing",
			1,
			"RightHandPinky1",
			1,
			"RightHandPinky2",
			1,
			"RightHandPinky3",
			1,
			"RightHandRing1",
			1,
			"RightHandRing2",
			1,
			"RightHandRing3",
			1,
			"RightHandMiddle1",
			1,
			"RightHandMiddle2",
			1,
			"RightHandMiddle3",
			1,
			"RightHandIndex1",
			1,
			"RightHandIndex2",
			1,
			"RightHandIndex3",
			1,
			"RightHandThumb1",
			1,
			"RightHandThumb2",
			1,
			"RightHandThumb3",
			1,
			"LeftShoulder",
			1,
			"LeftArm",
			1,
			"LeftArmRoll",
			1,
			"LeftForeArm",
			1,
			"LeftForeArmRoll",
			1,
			"LeftHand",
			1,
			"LeftHandRing",
			1,
			"LeftHandPinky1",
			1,
			"LeftHandPinky2",
			1,
			"LeftHandPinky3",
			1,
			"LeftHandRing1",
			1,
			"LeftHandRing2",
			1,
			"LeftHandRing3",
			1,
			"LeftHandMiddle1",
			1,
			"LeftHandMiddle2",
			1,
			"LeftHandMiddle3",
			1,
			"LeftHandIndex1",
			1,
			"LeftHandIndex2",
			1,
			"LeftHandIndex3",
			1,
			"LeftHandThumb1",
			1,
			"LeftHandThumb2",
			1,
			"LeftHandThumb3",
			1,
			"Spine",
			0.69999999,
			"Spine1",
			0.69999999,
			"Spine2",
			0.89999998,
			"Spine3",
			0.89999998
		};
		AX87_pistol_arms[]=
		{
			"LeftShoulder",
			1,
			"LeftArm",
			1,
			"LeftArmRoll",
			1,
			"LeftForeArm",
			1,
			"LeftForeArmRoll",
			1,
			"LeftHand",
			1,
			"LeftHandRing",
			1,
			"LeftHandPinky1",
			1,
			"LeftHandPinky2",
			1,
			"LeftHandPinky3",
			1,
			"LeftHandRing1",
			1,
			"LeftHandRing2",
			1,
			"LeftHandRing3",
			1,
			"LeftHandMiddle1",
			1,
			"LeftHandMiddle2",
			1,
			"LeftHandMiddle3",
			1,
			"LeftHandIndex1",
			1,
			"LeftHandIndex2",
			1,
			"LeftHandIndex3",
			1,
			"LeftHandThumb1",
			1,
			"LeftHandThumb2",
			1,
			"LeftHandThumb3",
			1
		};
	};
	class States
	{
		class AX87_Sprint_base: Default
		{
			actions="NoActions";
			canPullTrigger=1;
			canBlendStep=1;
			connectAs="";
			connectFrom[]={};
			connectTo[]={};
			disableWeapons=1;
			disableWeaponslong=1;
			enableBinocular=1;
			enableMissile=1;
			enableOptics=1;
			equivalentTo="";
			file=QPATHTOF(data\anim_base.rtm);
			forceAim=0;
			headBobMode=0;
			headBobStrength=0.40000001;
			interpolateFrom[]={};
			interpolateTo[]={};
			interpolateWith[]={};
			interpolationRestart=0;
			interpolationSpeed=4;
			mask="AX87_Carry_arms";
			looped=1;
			minPlayTime=1;
			preload=1;
			ragdoll=0;
			relSpeedMax=1;
			relSpeedMin=1;
			showHandGun=0;
			showItemInHand=0;
			showItemInRightHand=0;
			showWeaponAim=0;
			soundEdge[]={0.5,1};
			soundEnabled=1;
			soundOverride="";
			speed=4;
			static=0;
			terminal=0;
			Walkcycles=1;
			weaponIK=1;
			leftHandIKBeg=0;
			leftHandIKCurve[]={0};
			leftHandIKEnd=0;
			rightHandIKBeg=0;
			rightHandIKCurve[]={0};
			rightHandIKEnd=0;
		};
		class AX87_Switch_pistol: AX87_Sprint_base
		{
			disableWeapons=1;
			disableWeaponslong=1;
			file = "\A3\anims_f\Data\Anim\Sdr\Mov\erc\stp\non\non\AmovPercMstpSnonWnonDnon_AmovPercMstpSrasWpstDnon";
			speed=9;
			interpolationSpeed=5;
			mask="AX87_pistol_arms";
			looped=0;
			weaponIK=1;
			leftHandIKBeg=0;
			leftHandIKCurve[]={0};
			leftHandIKEnd=0;
			rightHandIKBeg=0;
			rightHandIKCurve[]={0};
			rightHandIKEnd=0;
		};
		class AX87_pistol: AX87_Sprint_base
		{
			canPullTrigger=1;
			disableWeapons=0;
			disableWeaponslong=0;
			enableOptics=2;
			file=QPATHTOF(data\anim_move.rtm);
			forceAim=0;
			speed=0;
			interpolationSpeed=7;
			mask="AX87_pistol_arms";
			showWeaponAim = 1;
			looped=1;
			weaponIK=2;
			leftHandIKBeg=0.3;
			leftHandIKCurve[]={0.3};
			leftHandIKEnd=0.3;
			rightHandIKBeg=1;
			rightHandIKCurve[]={1};
			rightHandIKEnd=1;
		};
	};
};